version: "3"

services:
  saturn3sample-django:
    restart: unless-stopped
    build: .
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=saturn3samples
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d saturn3samples" ]
      interval: 10s
      timeout: 5s
      retries: 5
